Contact  adding
mwakiogeofrey/PORTIFOLIO-PROJECT pull request #3
Opened 2023-03-28 15:43 UTC by mwakiogeofrey

The project is about adding contact to my portfolio

2023-03-28 18:35 UTC, LionRouge1 requested changes
Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good collaboration :+1: 
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 18:35 UTC, LionRouge1 commented on index.html
> +        please get in touch.</h1>
- [OPTIONAL] Since this is not the main title of our webpage, It will be better to use  `hx (examples: <h2>,<h3>,<h4>, etc...)` tag instead of an `h1` tag for semantics reasons. It's also advised to use only once an `h1` tag on a webpage

2023-03-28 18:35 UTC, LionRouge1 commented on index.html
> +        <form class="myall" action="/my-handling-form-page" method="post">
- [ ] Nice work using the `action` and `method` attributes for the `form` tag :100: However according to the project requirement, data is collected by using the [Formspree service](https://formspree.io/html). Kindly integrate your form with [Formspree service](https://formspree.io/html) by setting your action value to be similar to `https://formspree.io/f/{form_id}`. The `form_id` will be given to you when you create an account with [Formspree service](https://formspree.io/html)
![Screenshot from 2023-03-28 18-29-13](https://user-images.githubusercontent.com/91142432/228333580-66c6de70-c855-4187-a957-4cb30c245617.png)

2023-03-28 18:35 UTC, LionRouge1 commented on index.html
> +              <input type="text" id="name" name="user_name" />
- [ ] Please remove the `label` tag and use `placeholder="Full Name"` as requested by the project requirement (see image). Placeholder text is displayed in the input field before the user enters a value. You can read more about it [here](https://www.w3schools.com/tags/att_input_placeholder.asp#:~:text=The%20placeholder%20attribute%20specifies%20a,the%20user%20enters%20a%20value.).

- [ ] Please make sure your name field accepts up to 30 chars as requested by the requirement (see image). You can do so by adding the `maxlength="30"` attribute.

- [ ] Kindly make sure that the form is not submitted when this field is empty as requested by the requirement (see image). You can do so by adding the `required` attribute.

![Screenshot from 2023-03-28 17-49-53](https://user-images.githubusercontent.com/91142432/228325202-8be1c7c7-6aa8-47e1-bd0a-0a10db6fcae9.png)

2023-03-28 18:35 UTC, LionRouge1 commented on index.html
> +              <input type="email" id="mail" name="user_email" />
- [ ] Same here too :point_up_2: just that we don't need to add the `maxlength` attribute here.

2023-03-28 18:35 UTC, LionRouge1 commented on index.html
> +                <textarea id="msg" name="user_message">Write me something...</textarea>
- [ ] Same here too :point_up_2: Just that here use `maxlength="500"` as requested by the requirement (Message fields accepts up to 500 chars)

2023-03-28 18:35 UTC, LionRouge1 commented on index.html
> +          </form>
[OPTIONAL]
- [ ] Please remove the `ul` and `li` tags from the `form` tag. Apart from being semantically correct, they are used together to create unordered lists.

2023-03-28 18:35 UTC, LionRouge1 commented on index.html
> +              <a href="http://medium"><li><i class="fa-brands fa-medium"></i></li></a>
- [ ] Nice work implementing the media icons it looks really good :clap: But please, the `a` tag should be in the `li` tag not the opposite for semantic reasons. Your code could look like this:
```sh
<ul>
    <li><a href="http://github"><i class="fa-brands fa-github"></a></li>
     <li><a href="http://linkedin"><i class="fa-brands fa-linkedin-in"></a></li>
      ...
</ul>
```

2023-03-28 18:35 UTC, LionRouge1 commented on style.css
> +}
- [ ] Please, stick to the design as much as possible (e.g., font, colors, images, text, margins) as required in the project requirement.

### Your design 
![Screenshot from 2023-03-28 18-19-08](https://user-images.githubusercontent.com/91142432/228332377-fa12fda0-ee68-44dd-aaab-f8e761dc345f.png)

### what it suppose to look like 
![Screenshot from 2023-03-28 17-13-59](https://user-images.githubusercontent.com/91142432/228332501-30124687-1839-4fbd-bc41-01f90ed14e77.png)

2023-03-29 14:29 UTC, Paul-tes reviewed
Kindly, I suggest you remove unnecessary spaces.

2023-03-29 14:29 UTC, Paul-tes commented on index.html
> +          </ul>
> I suggest you, don't leave any free space unless the elements have basic(semantical) differences. likewise, I inlined only one free space there are also other unnecessary spaces to remove in this file.

2023-03-29 16:22 UTC, Strangeal requested changes
Hi @mwakiogeofrey, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

 ## Highlights


 ## Required Changes ♻️
- [ ] Please be sure to stick to the Figma template as much as possible. Currently, you have some space on the right side of the design so, please adjust that and make it look like the Figma template.
Your design:
<img width="326" alt="Screenshot 2023-03-29 at 09 07 10" src="https://user-images.githubusercontent.com/107192076/228603306-7d3dbdf3-574d-457c-b7b3-de0e7f1d6a0d.png">

Figma:
<img width="299" alt="Screenshot 2023-03-29 at 09 11 59" src="https://user-images.githubusercontent.com/107192076/228603404-1250e675-af39-49d0-a32b-b5529314ec21.png">

- [ ] Please make sure the social icons are the same as it is on the Figma template.
Your design:
<img width="326" alt="Screenshot 2023-03-29 at 09 12 43" src="https://user-images.githubusercontent.com/107192076/228603688-3bba8adb-6da6-4ce5-84e0-aceb9362fd21.png">

Figma:
<img width="346" alt="Screenshot 2023-03-29 at 07 28 05" src="https://user-images.githubusercontent.com/107192076/228603767-89fcefa5-0f52-4232-a144-a7dcb081e053.png">



_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 16:22 UTC, Strangeal commented on index.html
> +            Full name
As specified by the previous reviewer. Please remove the `label` tag and use `placeholder="Full Name"` as requested by the project requirement (see image). Placeholder text is displayed in the input field before the user enters a value. You can read more about it [here](https://www.w3schools.com/tags/att_input_placeholder.asp#:~:text=The%20placeholder%20attribute%20specifies%20a,the%20user%20enters%20a%20value.).
![rev](https://user-images.githubusercontent.com/107192076/228598482-b9dca851-3b21-42c1-a856-2826fe290961.png)

2023-03-29 16:22 UTC, Strangeal commented on index.html
> +          </label>
Kindly refer back to the comment above and apply the same here.

2023-03-29 16:22 UTC, Strangeal commented on index.html
> +          method="post">
Please remove this `form` element as you have two of them in here. You only need one.

2023-03-30 10:03 UTC, LionRouge1 approved these changes
Hi @mwakiogeofrey, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-03-30 10:03 UTC, LionRouge1 commented on index.html
> +            <input class="input_name" type="text" name="name" value="Mwakio" id="Full Name" placeholder="full name"
[OPTIONAL]
- [ ] We want to get information from users not set our own information. Setting `value` attribute will always send the text of the attribute `value` instead of what the user enters. So kindly remove `value` attribute for this input in order to get the exact data entered by our visitors.

2023-03-30 10:03 UTC, LionRouge1 commented on index.html
> +            <input class="input_mail" type="email" name="user_email" value="mwakiogeofrey579@gmail.com" placeholder="example@gmai.com" required>
- [ ] Same here too :point_up_2:

2023-04-01 01:17 UTC, merged