Desktop version portfolio
mwakiogeofrey/PORTIFOLIO-PROJECT pull request #5
Opened 2023-03-31 02:48 UTC by mwakiogeofrey

The projects is about changing the mobile version portfolio  to desktop version using media queries

2023-03-31 04:00 UTC, emmiiorji requested changes
Hi @mwakiogeofrey, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/229019315-5cc590f9-1f04-4d0f-86a3-75860279447b.gif'/>
</div>


## Good Highlights✔️

- Good use of media queries for the desktop breakpoint of the CSS
- Proper use of background images


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 19:24 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @mwakiogeofrey 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

## Highlights 🌟

- ✔️ PR Descriptions 
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 19:24 UTC, abdulhamiid commented on index.html
> +          </ul>
Please Let's fix the issues with the alignment of this section as requested by the previous reviewer. 👍🤗

Figma (contents are aligned)
![image](https://user-images.githubusercontent.com/78251927/229206904-3511ae51-4ef5-4414-a561-c183a697a849.png)

Your design
![image](https://user-images.githubusercontent.com/78251927/229206732-11f6d238-0ad2-4b19-82d1-52dbd49a1efa.png)

2023-03-31 19:24 UTC, abdulhamiid commented on index.html
> +          </form>
As requested by the previous reviewer, please kindly fix the alignment of this section so that your work replicates the design as much as possible using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md).

Figma
![image](https://user-images.githubusercontent.com/78251927/229207455-ef9c82e6-7ed7-47ac-b672-32c7c1dcf70d.png)


Your design
![image](https://user-images.githubusercontent.com/78251927/229207914-852aaf87-d131-4f56-b93c-61a8cc3fc64d.png)

2023-03-31 19:24 UTC, abdulhamiid commented on index.html
> +           </footer>
Your design
![image](https://user-images.githubusercontent.com/78251927/229208376-b705e0ce-d8c6-4fe4-aa86-5804a1217874.png)

Figma
![image](https://user-images.githubusercontent.com/78251927/229208500-83c45dad-32fd-4e97-afea-830b7e05b82e.png)

Please kindly adjust the spacing between the element to match the template on Figma

2023-03-31 19:24 UTC, abdulhamiid commented on style.css
>  }
As requested by the previous reviewer, It is important that the mobile version remains responsive until the desktop version(768px or higher).

Let's follow the project core requirements for professional projects, and if we practice from our learning phase, it will be easier in the future at the industry level. Here is an article on [The importance of understanding software requirements](https://www.freecodecamp.org/news/why-understanding-software-requirements-matter-to-you-as-a-software-engineer/)

Your design at (728px) 
![image](https://user-images.githubusercontent.com/78251927/229209551-2d3f9481-522c-4dfc-a462-7e2046ebbe28.png)

2023-04-01 02:06 UTC, V-Blaze requested changes
## Hi @MasumaJaffery , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- UI Looks great✔
- You implemented some of the changes from the previous reviewer  ✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 02:06 UTC, V-Blaze commented on index.html
> +            <h1 class="orange">See project</h1>
- [ ] You have done a great job so far, But here is one important aspect of your project you can still improve on before moving to the next milestone. 😄 👍 👍 
 - - As explained by the previous reviewer, you need to implement the hover state on each of your project cards. By default in the desktop view, the `See Project button` is hidden, but when a user hovers over a project, the `See project button`  should appear on the bottom of the project card.
 - - Currently, the see project button is not visible on your website even when a user hovers or clicks on a project, That's not good for the user experience as users can't see any button to click if they want to explore your project.
 - Screenshot for reference 'Taken from the previous reviewer:
 
![image](https://user-images.githubusercontent.com/107632780/229260568-36cdbe50-1861-45b4-8c5c-c6231ae50c88.png)

- - You can always as for guidance by leaving a comment under this pull request or reaching out to your peers or mentors on slack. 😄 😄

2023-04-01 07:01 UTC, AlphaNtihinduka requested changes
## Hi @mwakiogeofrey 🙋‍♂️
Good job working on implementing the changes required by the previous reviewer. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is not yet professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- Kindly consider the inline review comment with a video

## Optional suggestions
- [ ] [OPTIONAL] I am excited that you considered the usage of `hx` tag for the headings. However, I suggest you consider using other `hx` tags instead of `h1` tags.  There should be only one `h1` tag on every page. This is because the screen readers target the `h1` tag which is the main heading and primarily found in the banner, to give people with poor sight, an overview of what the page is the website is all about ☺️.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-04-01 10:14 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @mwakiogeofrey   
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 10:14 UTC, iambenkis commented on index.html
> +        </section>
- [ ] I know that is going to be a fifth request 😄 but I hope it is the last one 👍. Kindly make sure the see button is well align with its item 👍 , it will make your design more beautiful 

![Capture](https://user-images.githubusercontent.com/80458199/229280138-dc1b5f69-d531-40da-96f9-af404ac9457d.PNG)

2023-04-01 10:24 UTC, MasumaJaffery commented
Hello Mwakiogeofrey/Portifolio-Project is not my Project! There's some
mistake to send me these emails!

On Sat, 1 Apr 2023, 3:14 pm Benjamin Kisenge, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: REQUIRED CHANGES ♻️♻️
>
> Hi @mwakiogeofrey <https://github.com/mwakiogeofrey>
> Good job so far! I know you worked hard to implement this project, I
> really appreciate the effort you put in! But there are some issues that you
> still need to work on to go to the next project but you are almost there!
>
> [image: almost-there]
> <https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif>
> To highlight 🍾
>
>    - All linters are passing ✔️
>    - Good commit history ✔️
>    - Follow GitHub flow ✔️
>
> Required changes ♻️ ♻️
>
>    - Check the comments under the review.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
>
> *Feel free to leave any questions or comments in the PR thread if
> something is not 100% clear. Please ping me @iambenkis
> <https://github.com/iambenkis> when you comment, so I can receive the
> notification or use Slack with the same name.*
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/mwakiogeofrey/PORTIFOLIO-PROJECT/pull/5#discussion_r1155089152>
> :
>
> > +            <li>Ruby</li>
> +          </ul>
> +          <div class="projectorange1">
> +            <h1 class="orange">See project</h1>
> +
> +          </div>
> +        </section>
>
>
>    - I know that is going to be a fifth request 😄 but I hope it is the
>    last one 👍. Kindly make sure the see button is well align with its
>    item 👍 , it will make your design more beautiful
>
> [image: Capture]
> <https://user-images.githubusercontent.com/80458199/229280138-dc1b5f69-d531-40da-96f9-af404ac9457d.PNG>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mwakiogeofrey/PORTIFOLIO-PROJECT/pull/5#pullrequestreview-1367840454>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4LZRBU454TFIXMVJBFN6JTW675YBANCNFSM6AAAAAAWOCLFU4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-01 12:29 UTC, amon-cofie approved these changes
Hi @mwakiogeofrey , 

## APPROVED 🟢 
I admire your resilience and determination 💪 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights

🚀 No linter errors
🚀 Great effort towards implementing required changes
🚀 Github flow used.

## Optional suggestions

[OPTIONAL] Please check the space to the left of the logo. Check the screenshots below: 

Your design: 
![image](https://user-images.githubusercontent.com/107795045/229288556-4438b1fa-35e2-4489-86be-4def05202070.png)

Figma design: 
![image](https://user-images.githubusercontent.com/107795045/229288614-bda214b3-4196-4c6a-b809-a9b450e982cb.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 17:20 UTC, merged